import mongoose from 'mongoose';
import Course from './course'; 
import connectDB from './db';


connectDB().then(() => {
  console.log('Connected to MongoDB');
  seedDatabase();
})
.catch(error => {
  console.error('Error connecting to MongoDB', error);
});


// Seed database function
async function seedDatabase() {
  try {
    // Remove all existing courses
    await Course.deleteMany({});
    console.log('All existing courses removed');

    // Add new courses
    const courses = [
      {
        courseCode: 'CS102',
        name: 'Data Structures',
        description: 'An intermediate course on data structures.',
        attributes: {
          availableCredits: 4,
          courseLevel: 'Intermediate',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'Computer Science',
          courseSubCategory: 'Data Structures',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'CA',
          County: 'Santa Clara',
          institution: 'Stanford University',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        courseCode: 'MATH201',
        name: 'Calculus I',
        description: 'An introductory course on calculus.',
        attributes: {
          availableCredits: 3,
          courseLevel: 'Beginner',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'Mathematics',
          courseSubCategory: 'Calculus',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'NY',
          County: 'New York',
          institution: 'New York University',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      // Add 18 more courses here in the same format
      {
        courseCode: 'PHY101',
        name: 'General Physics',
        description: 'An introductory course on physics.',
        attributes: {
          availableCredits: 4,
          courseLevel: 'Beginner',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'Physics',
          courseSubCategory: 'Basics',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'MA',
          County: 'Middlesex',
          institution: 'MIT',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        courseCode: 'CHEM101',
        name: 'Organic Chemistry',
        description: 'An introductory course on organic chemistry.',
        attributes: {
          availableCredits: 3,
          courseLevel: 'Beginner',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'Chemistry',
          courseSubCategory: 'Organic',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'CA',
          County: 'Los Angeles',
          institution: 'UCLA',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        courseCode: 'BIO101',
        name: 'Biology I',
        description: 'An introductory course on biology.',
        attributes: {
          availableCredits: 4,
          courseLevel: 'Beginner',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'Biology',
          courseSubCategory: 'Basics',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'TX',
          County: 'Harris',
          institution: 'Rice University',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        courseCode: 'HIST101',
        name: 'World History',
        description: 'An introductory course on world history.',
        attributes: {
          availableCredits: 3,
          courseLevel: 'Beginner',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'History',
          courseSubCategory: 'World History',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'IL',
          County: 'Cook',
          institution: 'University of Chicago',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        courseCode: 'ENG101',
        name: 'English Composition',
        description: 'An introductory course on English composition.',
        attributes: {
          availableCredits: 3,
          courseLevel: 'Beginner',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'English',
          courseSubCategory: 'Composition',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'NY',
          County: 'New York',
          institution: 'Columbia University',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        courseCode: 'PSY101',
        name: 'Introduction to Psychology',
        description: 'An introductory course on psychology.',
        attributes: {
          availableCredits: 3,
          courseLevel: 'Beginner',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'Psychology',
          courseSubCategory: 'Basics',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'CA',
          County: 'Santa Clara',
          institution: 'Stanford University',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        courseCode: 'ECON101',
        name: 'Principles of Economics',
        description: 'An introductory course on economics.',
        attributes: {
          availableCredits: 4,
          courseLevel: 'Beginner',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'Economics',
          courseSubCategory: 'Principles',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'MA',
          County: 'Middlesex',
          institution: 'Harvard University',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        courseCode: 'PHIL101',
        name: 'Introduction to Philosophy',
        description: 'An introductory course on philosophy.',
        attributes: {
          availableCredits: 3,
          courseLevel: 'Beginner',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'Philosophy',
          courseSubCategory: 'Basics',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'IL',
          County: 'Cook',
          institution: 'University of Chicago',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        courseCode: 'SOC101',
        name: 'Introduction to Sociology',
        description: 'An introductory course on sociology.',
        attributes: {
          availableCredits: 3,
          courseLevel: 'Beginner',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'Sociology',
          courseSubCategory: 'Basics',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'NY',
          County: 'New York',
          institution: 'Columbia University',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        courseCode: 'MUS101',
        name: 'Music Theory',
        description: 'An introductory course on music theory.',
        attributes: {
          availableCredits: 3,
          courseLevel: 'Beginner',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'Music',
          courseSubCategory: 'Theory',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'CA',
          County: 'Los Angeles',
          institution: 'UCLA',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        courseCode: 'ART101',
        name: 'Art History',
        description: 'An introductory course on art history.',
        attributes: {
          availableCredits: 3,
          courseLevel: 'Beginner',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'Art',
          courseSubCategory: 'History',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'NY',
          County: 'New York',
          institution: 'New York University',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        courseCode: 'CS201',
        name: 'Algorithms',
        description: 'An intermediate course on algorithms.',
        attributes: {
          availableCredits: 4,
          courseLevel: 'Intermediate',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'Computer Science',
          courseSubCategory: 'Algorithms',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'CA',
          County: 'Santa Clara',
          institution: 'Stanford University',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        courseCode: 'CS301',
        name: 'Operating Systems',
        description: 'An advanced course on operating systems.',
        attributes: {
          availableCredits: 4,
          courseLevel: 'Advanced',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'Computer Science',
          courseSubCategory: 'Systems',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'CA',
          County: 'Santa Clara',
          institution: 'Stanford University',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        courseCode: 'MATH301',
        name: 'Linear Algebra',
        description: 'An advanced course on linear algebra.',
        attributes: {
          availableCredits: 4,
          courseLevel: 'Advanced',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'Mathematics',
          courseSubCategory: 'Algebra',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'MA',
          County: 'Middlesex',
          institution: 'Harvard University',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        courseCode: 'PHYS301',
        name: 'Quantum Mechanics',
        description: 'An advanced course on quantum mechanics.',
        attributes: {
          availableCredits: 4,
          courseLevel: 'Advanced',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'Physics',
          courseSubCategory: 'Quantum',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'CA',
          County: 'Santa Clara',
          institution: 'Stanford University',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        courseCode: 'CHEM301',
        name: 'Physical Chemistry',
        description: 'An advanced course on physical chemistry.',
        attributes: {
          availableCredits: 4,
          courseLevel: 'Advanced',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'Chemistry',
          courseSubCategory: 'Physical',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'NY',
          County: 'New York',
          institution: 'Columbia University',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        courseCode: 'BIO301',
        name: 'Genetics',
        description: 'An advanced course on genetics.',
        attributes: {
          availableCredits: 4,
          courseLevel: 'Advanced',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'Biology',
          courseSubCategory: 'Genetics',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'TX',
          County: 'Harris',
          institution: 'Rice University',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        courseCode: 'HIST301',
        name: 'American History',
        description: 'An advanced course on American history.',
        attributes: {
          availableCredits: 4,
          courseLevel: 'Advanced',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'History',
          courseSubCategory: 'American History',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'IL',
          County: 'Cook',
          institution: 'University of Chicago',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        courseCode: 'ENG301',
        name: 'Modern English Literature',
        description: 'An advanced course on modern English literature.',
        attributes: {
          availableCredits: 4,
          courseLevel: 'Advanced',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'English',
          courseSubCategory: 'Literature',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'NY',
          County: 'New York',
          institution: 'New York University',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        courseCode: 'PSY301',
        name: 'Clinical Psychology',
        description: 'An advanced course on clinical psychology.',
        attributes: {
          availableCredits: 4,
          courseLevel: 'Advanced',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'Psychology',
          courseSubCategory: 'Clinical',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'CA',
          County: 'Santa Clara',
          institution: 'Stanford University',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        courseCode: 'ECON301',
        name: 'Macroeconomics',
        description: 'An advanced course on macroeconomics.',
        attributes: {
          availableCredits: 4,
          courseLevel: 'Advanced',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'Economics',
          courseSubCategory: 'Macroeconomics',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'MA',
          County: 'Middlesex',
          institution: 'Harvard University',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
      {
        courseCode: 'PHIL301',
        name: 'Ethics',
        description: 'An advanced course on ethics.',
        attributes: {
          availableCredits: 3,
          courseLevel: 'Advanced',
          maxGPAWeight: 4,
          courseLength: 'Semester',
          categoryType: 'Core',
          courseCategory: 'Philosophy',
          courseSubCategory: 'Ethics',
          createdOn: new Date(),
          updatedOn: new Date(),
          state: 'IL',
          County: 'Cook',
          institution: 'University of Chicago',
        },
        reviews: [],
        faqs: [],
        expiryDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        createdOn: new Date(),
        updatedOn: new Date(),
      },
    ];

    await Course.insertMany(courses);
    console.log('New courses added successfully');

    // Close the database connection
    mongoose.connection.close();
  } catch (error) {
    console.error('Error seeding the database', error);
    mongoose.connection.close();
  }
}
